# Configuración de Atlassian para Proyecto VFI

atlassian:
  base_url: "https://bit2bit.atlassian.net"
  email: ""  # Configurar con tu email
  api_token: ""  # Configurar con tu API token
  
jira:
  enabled: true
  project_key: "VFI"
  default_issue_type: "Task"
  auto_create_issues: true
  board_url: "https://bit2bit.atlassian.net/jira/software/c/projects/VFI/boards/199"
  
confluence:
  enabled: true
  space_key: "VFI"
  auto_sync_docs: true
  home_page_id: "17400211"
  base_url: "https://bit2bit.atlassian.net/wiki/spaces/VFI"
  sync_folders:
    - "01Doc"
    
rovo:
  enabled: true
  cli_path: "acli"  # Usar Atlassian CLI
  auto_context: true
  
# Configuración específica para AI Dev Framework
framework:
  project_name: "AI Dev Framework"
  description: "Framework de Desarrollo Inteligente para Proyectos con IA"
  version: "1.0.0"
  confluence_pages:
    - title: "AI Dev Framework - Guía Completa"
      template: "framework_overview"
    - title: "Instalación y Configuración"
      template: "installation_guide"
    - title: "Casos de Uso y Ejemplos"
      template: "use_cases"
    - title: "Integración con Rovo CLI"
      template: "rovo_integration" 